print('***** Analizando Uma String ******')
nome = str(input('Digite seu nome:')).strip()
print('Seu nome em Maiúsculas:{}'.format(nome.upper()))
print('Seu nome em minúsculas:{}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find('   ')))
