n = str(input('Digite seu nome completo:')).strip()
nome = n.split()
print('Ola,prazer em te conhecer')
print('Seu primeiro nome é {}'.format(nome[0]).title())
print('E seu último nome é {}'.format(nome[len(nome)-1]).title())
